import { BAIT_SUGGESTIONS, RIG_SUGGESTIONS } from './constants'
import { LEGAL_SIZE_RULES, type RegionCode } from '../types/species'

export interface SpeciesInfo {
  id: string
  commonName: string
  scientificName?: string
  description: string
  waterType: 'saltwater' | 'freshwater' | 'both'
  habitat: string
  averageWeightKg: { min: number; max: number }
  trophyWeightKg: number
  averageLengthCm: { min: number; max: number }
  worldRecord?: { weightKg: number; location: string; year: number }
  bestSeason?: string
  bestTime?: string
}

// Comprehensive species database
export const SPECIES_INFO: Record<string, SpeciesInfo> = {
  // SALTWATER
  'Bass (Sea)': {
    id: 'european_sea_bass',
    commonName: 'Bass (Sea)',
    scientificName: 'Dicentrarchus labrax',
    description: 'The European sea bass is one of the most prized sport fish in UK waters. Known for their fighting ability and excellent eating quality, they are a target species for many anglers.',
    waterType: 'saltwater',
    habitat: 'Rocky shores, estuaries, harbours, and sandy beaches. Often found around structures and in surf zones.',
    averageWeightKg: { min: 0.5, max: 2 },
    trophyWeightKg: 4,
    averageLengthCm: { min: 30, max: 50 },
    worldRecord: { weightKg: 12.0, location: 'Atlantic Coast', year: 1986 },
    bestSeason: 'May to October',
    bestTime: 'Dawn and dusk, especially on rising tides',
  },
  'Mackerel': {
    id: 'atlantic_mackerel',
    commonName: 'Mackerel',
    scientificName: 'Scomber scombrus',
    description: 'Fast-swimming pelagic fish that arrive in UK waters during summer. Excellent sport on light tackle and great eating fresh.',
    waterType: 'saltwater',
    habitat: 'Open water, often near the surface. Found around piers, breakwaters, and from boats.',
    averageWeightKg: { min: 0.2, max: 0.5 },
    trophyWeightKg: 1.5,
    averageLengthCm: { min: 25, max: 35 },
    worldRecord: { weightKg: 2.9, location: 'Norway', year: 1992 },
    bestSeason: 'June to October',
    bestTime: 'Early morning and evening',
  },
  'Cod': {
    id: 'atlantic_cod',
    commonName: 'Cod',
    scientificName: 'Gadus morhua',
    description: 'A cold-water species that was once abundant in UK waters. Still a popular target, especially in winter months from beaches and boats.',
    waterType: 'saltwater',
    habitat: 'Deep water over sand, mud, and rough ground. Moves inshore during winter.',
    averageWeightKg: { min: 1, max: 5 },
    trophyWeightKg: 15,
    averageLengthCm: { min: 40, max: 80 },
    worldRecord: { weightKg: 47.0, location: 'Norway', year: 2013 },
    bestSeason: 'October to February',
    bestTime: 'Night fishing, especially during storms',
  },
  'Pollock': {
    id: 'pollock',
    commonName: 'Pollock',
    scientificName: 'Pollachius pollachius',
    description: 'A powerful fish found around wrecks and reefs. Excellent sport on lures and great eating when fresh.',
    waterType: 'saltwater',
    habitat: 'Wrecks, reefs, and rocky ground. Often mid-water hunters.',
    averageWeightKg: { min: 1, max: 4 },
    trophyWeightKg: 8,
    averageLengthCm: { min: 40, max: 70 },
    worldRecord: { weightKg: 12.4, location: 'Norway', year: 1995 },
    bestSeason: 'All year, best April to October',
    bestTime: 'Slack water periods',
  },
  'Coalfish': {
    id: 'coalfish',
    commonName: 'Coalfish',
    scientificName: 'Pollachius virens',
    description: 'Also known as saithe or coley. Similar to pollock but darker in colour. Strong fighters found in northern waters.',
    waterType: 'saltwater',
    habitat: 'Wrecks, reefs, and open water. Often in large shoals.',
    averageWeightKg: { min: 1, max: 5 },
    trophyWeightKg: 10,
    averageLengthCm: { min: 40, max: 80 },
    worldRecord: { weightKg: 22.7, location: 'Norway', year: 1987 },
    bestSeason: 'All year',
    bestTime: 'Daytime, especially in clear water',
  },
  'Wrasse (Ballan)': {
    id: 'ballan_wrasse',
    commonName: 'Ballan Wrasse',
    scientificName: 'Labrus bergylta',
    description: 'The largest UK wrasse species. Beautifully coloured fish that live among rocks and kelp. Powerful fighters.',
    waterType: 'saltwater',
    habitat: 'Rocky shores, kelp beds, and harbour walls.',
    averageWeightKg: { min: 0.5, max: 2 },
    trophyWeightKg: 4,
    averageLengthCm: { min: 25, max: 45 },
    worldRecord: { weightKg: 4.4, location: 'UK', year: 2009 },
    bestSeason: 'May to October',
    bestTime: 'High water, calm conditions',
  },
  'Plaice': {
    id: 'plaice',
    commonName: 'Plaice',
    scientificName: 'Pleuronectes platessa',
    description: 'A popular flatfish with distinctive orange spots. Excellent eating and found on sandy ground.',
    waterType: 'saltwater',
    habitat: 'Sandy and shingle seabeds, often in shallow water.',
    averageWeightKg: { min: 0.3, max: 1 },
    trophyWeightKg: 3,
    averageLengthCm: { min: 25, max: 45 },
    worldRecord: { weightKg: 4.5, location: 'Sweden', year: 1989 },
    bestSeason: 'March to October',
    bestTime: 'Daylight hours, flood tide',
  },
  'Flounder': {
    id: 'flounder',
    commonName: 'Flounder',
    scientificName: 'Platichthys flesus',
    description: 'A flatfish that tolerates brackish water and is often found in estuaries. Good sport on light tackle.',
    waterType: 'saltwater',
    habitat: 'Estuaries, harbours, and sandy beaches. Tolerates freshwater.',
    averageWeightKg: { min: 0.2, max: 0.8 },
    trophyWeightKg: 2,
    averageLengthCm: { min: 20, max: 40 },
    worldRecord: { weightKg: 2.6, location: 'Denmark', year: 1999 },
    bestSeason: 'September to March',
    bestTime: 'Flood tide, especially after dark',
  },
  'Rays (Thornback)': {
    id: 'thornback_ray',
    commonName: 'Thornback Ray',
    scientificName: 'Raja clavata',
    description: 'The most common ray species in UK waters. Named for the thorny spines on their back and tail.',
    waterType: 'saltwater',
    habitat: 'Sandy and muddy seabeds, often in shallow water.',
    averageWeightKg: { min: 2, max: 6 },
    trophyWeightKg: 12,
    averageLengthCm: { min: 50, max: 80 },
    worldRecord: { weightKg: 14.5, location: 'UK', year: 1981 },
    bestSeason: 'April to October',
    bestTime: 'Night tides, especially spring tides',
  },
  'Smoothhound': {
    id: 'smoothhound',
    commonName: 'Smoothhound',
    scientificName: 'Mustelus mustelus',
    description: 'A small shark species that provides excellent sport. Known for powerful runs and stamina.',
    waterType: 'saltwater',
    habitat: 'Sandy and muddy ground, often in shallow water.',
    averageWeightKg: { min: 3, max: 8 },
    trophyWeightKg: 15,
    averageLengthCm: { min: 80, max: 120 },
    worldRecord: { weightKg: 15.0, location: 'UK', year: 1998 },
    bestSeason: 'May to September',
    bestTime: 'Night fishing on spring tides',
  },
  'Tope': {
    id: 'tope',
    commonName: 'Tope',
    scientificName: 'Galeorhinus galeus',
    description: 'A true shark species and one of the UK\'s premier sport fish. Powerful, fast, and can reach impressive sizes.',
    waterType: 'saltwater',
    habitat: 'Open water over sand and mud. Often found in channels and tide races.',
    averageWeightKg: { min: 10, max: 25 },
    trophyWeightKg: 40,
    averageLengthCm: { min: 100, max: 150 },
    worldRecord: { weightKg: 44.5, location: 'UK', year: 1991 },
    bestSeason: 'May to September',
    bestTime: 'Tide runs, especially at dawn/dusk',
  },
  'Conger Eel': {
    id: 'conger_eel',
    commonName: 'Conger Eel',
    scientificName: 'Conger conger',
    description: 'The largest eel species in UK waters. Powerful fighters found in wrecks and rocky lairs.',
    waterType: 'saltwater',
    habitat: 'Wrecks, rocky holes, and harbour walls.',
    averageWeightKg: { min: 5, max: 20 },
    trophyWeightKg: 50,
    averageLengthCm: { min: 100, max: 200 },
    worldRecord: { weightKg: 61.5, location: 'UK', year: 2015 },
    bestSeason: 'All year, best in summer',
    bestTime: 'Night fishing',
  },
  'Dogfish (Lesser Spotted)': {
    id: 'lesser_spotted_dogfish',
    commonName: 'Lesser Spotted Dogfish',
    scientificName: 'Scyliorhinus canicula',
    description: 'Also known as the rough hound. A small shark species common around UK coasts. Often the first shark species caught by beginners.',
    waterType: 'saltwater',
    habitat: 'Sandy and rocky ground, from shallow to deep water.',
    averageWeightKg: { min: 0.5, max: 1.5 },
    trophyWeightKg: 2,
    averageLengthCm: { min: 40, max: 70 },
    worldRecord: { weightKg: 2.1, location: 'UK', year: 2005 },
    bestSeason: 'All year',
    bestTime: 'Night fishing',
  },
  'Mullet (Thick-lipped)': {
    id: 'thick_lipped_mullet',
    commonName: 'Thick-lipped Grey Mullet',
    scientificName: 'Chelon labrosus',
    description: 'One of the most challenging UK species to catch. Wary, intelligent fish that require finesse and patience.',
    waterType: 'saltwater',
    habitat: 'Harbours, estuaries, and coastal lagoons. Often seen cruising near the surface.',
    averageWeightKg: { min: 0.5, max: 2 },
    trophyWeightKg: 4,
    averageLengthCm: { min: 30, max: 50 },
    worldRecord: { weightKg: 6.5, location: 'UK', year: 1979 },
    bestSeason: 'May to October',
    bestTime: 'Warm, calm days',
  },
  'Garfish': {
    id: 'garfish',
    commonName: 'Garfish',
    scientificName: 'Belone belone',
    description: 'A spectacular surface-feeding fish with a distinctive long beak. Acrobatic fighters that leap when hooked.',
    waterType: 'saltwater',
    habitat: 'Surface waters, often around piers and rocky headlands.',
    averageWeightKg: { min: 0.2, max: 0.5 },
    trophyWeightKg: 1,
    averageLengthCm: { min: 40, max: 60 },
    worldRecord: { weightKg: 1.4, location: 'Norway', year: 2001 },
    bestSeason: 'May to September',
    bestTime: 'Calm, sunny days',
  },
  'Black Bream': {
    id: 'black_bream',
    commonName: 'Black Bream',
    scientificName: 'Spondyliosoma cantharus',
    description: 'A beautiful silver-grey fish that arrives in UK waters during summer to spawn. Excellent sport on light tackle.',
    waterType: 'saltwater',
    habitat: 'Wrecks, reefs, and rough ground. Often in large shoals.',
    averageWeightKg: { min: 0.3, max: 1 },
    trophyWeightKg: 2,
    averageLengthCm: { min: 20, max: 35 },
    worldRecord: { weightKg: 3.1, location: 'UK', year: 2000 },
    bestSeason: 'April to July',
    bestTime: 'Slack water, especially at anchor',
  },
  'Whiting': {
    id: 'whiting',
    commonName: 'Whiting',
    scientificName: 'Merlangius merlangus',
    description: 'A member of the cod family that provides good winter sport. Often caught in numbers from beaches.',
    waterType: 'saltwater',
    habitat: 'Sandy and muddy ground, from shallow to deep water.',
    averageWeightKg: { min: 0.2, max: 0.8 },
    trophyWeightKg: 2,
    averageLengthCm: { min: 20, max: 40 },
    worldRecord: { weightKg: 2.9, location: 'UK', year: 1981 },
    bestSeason: 'October to March',
    bestTime: 'Night fishing',
  },

  // FRESHWATER / COARSE
  'Carp (Common)': {
    id: 'common_carp',
    commonName: 'Common Carp',
    scientificName: 'Cyprinus carpio',
    description: 'The most popular coarse fishing target in the UK. Intelligent, powerful, and can grow to impressive sizes.',
    waterType: 'freshwater',
    habitat: 'Lakes, ponds, canals, and slow-moving rivers. Prefer weedy areas with cover.',
    averageWeightKg: { min: 2, max: 10 },
    trophyWeightKg: 20,
    averageLengthCm: { min: 40, max: 80 },
    worldRecord: { weightKg: 48.0, location: 'France', year: 2019 },
    bestSeason: 'May to October',
    bestTime: 'Early morning and late evening',
  },
  'Carp (Mirror)': {
    id: 'mirror_carp',
    commonName: 'Mirror Carp',
    scientificName: 'Cyprinus carpio',
    description: 'A variant of common carp with irregular, mirror-like scales. Highly prized by specimen hunters.',
    waterType: 'freshwater',
    habitat: 'Lakes, ponds, and gravel pits. Often found in deeper water during day.',
    averageWeightKg: { min: 2, max: 12 },
    trophyWeightKg: 25,
    averageLengthCm: { min: 40, max: 90 },
    worldRecord: { weightKg: 51.2, location: 'Hungary', year: 2018 },
    bestSeason: 'May to October',
    bestTime: 'Night sessions often most productive',
  },
  'Pike': {
    id: 'northern_pike',
    commonName: 'Pike',
    scientificName: 'Esox lucius',
    description: 'The apex predator of UK freshwaters. Aggressive hunters with impressive teeth and explosive strikes.',
    waterType: 'freshwater',
    habitat: 'Lakes, rivers, canals, and drains. Ambush predators that lurk near cover.',
    averageWeightKg: { min: 2, max: 8 },
    trophyWeightKg: 15,
    averageLengthCm: { min: 60, max: 100 },
    worldRecord: { weightKg: 25.0, location: 'Germany', year: 1986 },
    bestSeason: 'October to March',
    bestTime: 'Early morning, overcast days',
  },
  'Zander': {
    id: 'zander',
    commonName: 'Zander',
    scientificName: 'Sander lucioperca',
    description: 'A predatory fish introduced to UK waters. Ghostly appearance with large eyes adapted for low-light hunting.',
    waterType: 'freshwater',
    habitat: 'Rivers, canals, and lakes. Prefer murky water and hunt at dawn/dusk.',
    averageWeightKg: { min: 1, max: 4 },
    trophyWeightKg: 8,
    averageLengthCm: { min: 40, max: 70 },
    worldRecord: { weightKg: 11.5, location: 'Finland', year: 2003 },
    bestSeason: 'All year, best autumn/winter',
    bestTime: 'Dusk and dawn, night fishing',
  },
  'Perch': {
    id: 'european_perch',
    commonName: 'Perch',
    scientificName: 'Perca fluviatilis',
    description: 'A beautifully marked predator with distinctive stripes. Aggressive feeders that provide great sport.',
    waterType: 'freshwater',
    habitat: 'Lakes, rivers, canals. Often found near structures and drop-offs.',
    averageWeightKg: { min: 0.2, max: 0.8 },
    trophyWeightKg: 2,
    averageLengthCm: { min: 15, max: 35 },
    worldRecord: { weightKg: 2.9, location: 'Netherlands', year: 2010 },
    bestSeason: 'All year, best autumn/winter',
    bestTime: 'Early morning and late afternoon',
  },
  'Roach': {
    id: 'roach',
    commonName: 'Roach',
    scientificName: 'Rutilus rutilus',
    description: 'One of the most common UK coarse fish. Beautiful silver fish with red fins. A traditional target for match anglers.',
    waterType: 'freshwater',
    habitat: 'Rivers, lakes, canals, and ponds. Shoal fish found at all depths.',
    averageWeightKg: { min: 0.1, max: 0.5 },
    trophyWeightKg: 1,
    averageLengthCm: { min: 15, max: 30 },
    worldRecord: { weightKg: 1.9, location: 'Germany', year: 1990 },
    bestSeason: 'All year',
    bestTime: 'Early morning, overcast days',
  },
  'Rudd': {
    id: 'rudd',
    commonName: 'Rudd',
    scientificName: 'Scardinius erythrophthalmus',
    description: 'Similar to roach but with more golden colouration and upturned mouth. Surface feeders in summer.',
    waterType: 'freshwater',
    habitat: 'Lakes, ponds, and slow rivers. Often near weed beds.',
    averageWeightKg: { min: 0.1, max: 0.5 },
    trophyWeightKg: 1.5,
    averageLengthCm: { min: 15, max: 30 },
    worldRecord: { weightKg: 2.1, location: 'Ireland', year: 2001 },
    bestSeason: 'May to September',
    bestTime: 'Warm evenings, surface feeding',
  },
  'Bream (Common)': {
    id: 'common_bream',
    commonName: 'Common Bream',
    scientificName: 'Abramis brama',
    description: 'A deep-bodied fish that feeds in large shoals. Popular match fishing target that can be caught in big numbers.',
    waterType: 'freshwater',
    habitat: 'Lakes, rivers, and canals. Bottom feeders on silty beds.',
    averageWeightKg: { min: 1, max: 4 },
    trophyWeightKg: 7,
    averageLengthCm: { min: 30, max: 50 },
    worldRecord: { weightKg: 9.4, location: 'UK', year: 1991 },
    bestSeason: 'May to October',
    bestTime: 'Dawn and dusk, night fishing',
  },
  'Tench': {
    id: 'tench',
    commonName: 'Tench',
    scientificName: 'Tinca tinca',
    description: 'The "doctor fish" - a beautiful green-bronze fish that fights hard. Traditional summer target.',
    waterType: 'freshwater',
    habitat: 'Weedy lakes, ponds, and slow rivers. Bottom feeders in silty areas.',
    averageWeightKg: { min: 1, max: 4 },
    trophyWeightKg: 7,
    averageLengthCm: { min: 30, max: 50 },
    worldRecord: { weightKg: 7.3, location: 'UK', year: 2001 },
    bestSeason: 'May to September',
    bestTime: 'Dawn, especially misty mornings',
  },
  'Barbel': {
    id: 'barbel',
    commonName: 'Barbel',
    scientificName: 'Barbus barbus',
    description: 'Powerful river fish known for unstoppable runs. One of the hardest fighting UK freshwater fish.',
    waterType: 'freshwater',
    habitat: 'Fast-flowing rivers with gravel beds. Often found in swims with good flow.',
    averageWeightKg: { min: 2, max: 6 },
    trophyWeightKg: 10,
    averageLengthCm: { min: 40, max: 70 },
    worldRecord: { weightKg: 9.4, location: 'UK', year: 2019 },
    bestSeason: 'June to November',
    bestTime: 'Dusk and into darkness',
  },
  'Chub': {
    id: 'chub',
    commonName: 'Chub',
    scientificName: 'Squalius cephalus',
    description: 'A versatile fish found in rivers and stillwaters. Will eat almost anything and provides year-round sport.',
    waterType: 'freshwater',
    habitat: 'Rivers, streams, and some stillwaters. Often under overhanging cover.',
    averageWeightKg: { min: 0.5, max: 2 },
    trophyWeightKg: 4,
    averageLengthCm: { min: 25, max: 45 },
    worldRecord: { weightKg: 4.2, location: 'UK', year: 2007 },
    bestSeason: 'All year',
    bestTime: 'Winter especially productive',
  },
  'Dace': {
    id: 'dace',
    commonName: 'Dace',
    scientificName: 'Leuciscus leuciscus',
    description: 'A small, fast-swimming river fish. Excellent sport on ultra-light tackle.',
    waterType: 'freshwater',
    habitat: 'Clean, fast-flowing rivers and streams.',
    averageWeightKg: { min: 0.05, max: 0.2 },
    trophyWeightKg: 0.5,
    averageLengthCm: { min: 12, max: 25 },
    worldRecord: { weightKg: 0.6, location: 'UK', year: 2002 },
    bestSeason: 'All year',
    bestTime: 'Daytime, especially in winter',
  },
  'Crucian Carp': {
    id: 'crucian_carp',
    commonName: 'Crucian Carp',
    scientificName: 'Carassius carassius',
    description: 'A beautiful golden fish and a true native species. Shy biters that require delicate presentation.',
    waterType: 'freshwater',
    habitat: 'Ponds, lakes, and canals. Prefer weedy, silty waters.',
    averageWeightKg: { min: 0.2, max: 0.8 },
    trophyWeightKg: 2,
    averageLengthCm: { min: 15, max: 30 },
    worldRecord: { weightKg: 2.1, location: 'UK', year: 2015 },
    bestSeason: 'May to September',
    bestTime: 'Warm, still evenings',
  },
  'Eel': {
    id: 'european_eel',
    commonName: 'Eel',
    scientificName: 'Anguilla anguilla',
    description: 'A mysterious fish that breeds in the Sargasso Sea. Now endangered but still occasionally caught.',
    waterType: 'freshwater',
    habitat: 'Rivers, lakes, ponds, and canals. Nocturnal bottom feeders.',
    averageWeightKg: { min: 0.3, max: 1 },
    trophyWeightKg: 3,
    averageLengthCm: { min: 40, max: 80 },
    worldRecord: { weightKg: 5.4, location: 'UK', year: 1978 },
    bestSeason: 'May to October',
    bestTime: 'Night fishing, warm nights',
  },
  'Catfish (Wels)': {
    id: 'wels_catfish',
    commonName: 'Wels Catfish',
    scientificName: 'Silurus glanis',
    description: 'Europe\'s largest freshwater fish. Introduced to UK waters and can grow to enormous sizes.',
    waterType: 'freshwater',
    habitat: 'Lakes and slow rivers. Bottom dwellers in deep water.',
    averageWeightKg: { min: 10, max: 40 },
    trophyWeightKg: 50,
    averageLengthCm: { min: 100, max: 200 },
    worldRecord: { weightKg: 144.0, location: 'Italy', year: 2010 },
    bestSeason: 'May to September',
    bestTime: 'Night fishing, warm weather',
  },

  // GAME
  'Trout (Brown)': {
    id: 'brown_trout',
    commonName: 'Brown Trout',
    scientificName: 'Salmo trutta',
    description: 'Native UK trout species. Beautiful fish with varied markings depending on habitat.',
    waterType: 'both',
    habitat: 'Rivers, streams, and lakes. Prefer clean, well-oxygenated water.',
    averageWeightKg: { min: 0.3, max: 1.5 },
    trophyWeightKg: 5,
    averageLengthCm: { min: 25, max: 45 },
    worldRecord: { weightKg: 19.1, location: 'New Zealand', year: 2013 },
    bestSeason: 'March to September (season varies)',
    bestTime: 'Evening rise, overcast days',
  },
  'Trout (Rainbow)': {
    id: 'rainbow_trout',
    commonName: 'Rainbow Trout',
    scientificName: 'Oncorhynchus mykiss',
    description: 'Introduced species now widespread in UK stillwaters. Acrobatic fighters that leap when hooked.',
    waterType: 'freshwater',
    habitat: 'Stocked lakes and reservoirs. Some river populations.',
    averageWeightKg: { min: 0.5, max: 2 },
    trophyWeightKg: 8,
    averageLengthCm: { min: 30, max: 50 },
    worldRecord: { weightKg: 21.8, location: 'Canada', year: 2009 },
    bestSeason: 'All year (stocked waters)',
    bestTime: 'Early morning, evening',
  },
  'Salmon (Atlantic)': {
    id: 'atlantic_salmon',
    commonName: 'Atlantic Salmon',
    scientificName: 'Salmo salar',
    description: 'The king of game fish. Powerful, acrobatic, and the ultimate freshwater challenge.',
    waterType: 'both',
    habitat: 'Rivers during spawning runs. Spend most of life at sea.',
    averageWeightKg: { min: 3, max: 8 },
    trophyWeightKg: 15,
    averageLengthCm: { min: 60, max: 90 },
    worldRecord: { weightKg: 35.9, location: 'Norway', year: 1928 },
    bestSeason: 'Varies by river (Feb-Oct)',
    bestTime: 'After rain, rising water',
  },
  'Sea Trout': {
    id: 'sea_trout',
    commonName: 'Sea Trout',
    scientificName: 'Salmo trutta',
    description: 'The sea-run form of brown trout. Mysterious night hunters that return to rivers to spawn.',
    waterType: 'both',
    habitat: 'Rivers and estuaries. Enter freshwater to spawn.',
    averageWeightKg: { min: 1, max: 3 },
    trophyWeightKg: 8,
    averageLengthCm: { min: 40, max: 60 },
    worldRecord: { weightKg: 16.7, location: 'Argentina', year: 1993 },
    bestSeason: 'May to September',
    bestTime: 'Night fishing, especially after dark',
  },
  'Grayling': {
    id: 'grayling',
    commonName: 'Grayling',
    scientificName: 'Thymallus thymallus',
    description: 'The "lady of the stream" with its distinctive sail-like dorsal fin. A winter favourite for fly fishers.',
    waterType: 'freshwater',
    habitat: 'Clean, fast-flowing rivers with gravel beds.',
    averageWeightKg: { min: 0.3, max: 0.8 },
    trophyWeightKg: 1.5,
    averageLengthCm: { min: 25, max: 40 },
    worldRecord: { weightKg: 2.9, location: 'UK', year: 2009 },
    bestSeason: 'October to March',
    bestTime: 'Midday in winter',
  },
}

// Get species info by name (handles variations)
export function getSpeciesInfo(speciesName: string): SpeciesInfo | null {
  if (!speciesName) return null
  
  // Direct match
  if (SPECIES_INFO[speciesName]) {
    return SPECIES_INFO[speciesName]
  }
  
  // Try case-insensitive match
  const lowerName = speciesName.toLowerCase()
  for (const [key, info] of Object.entries(SPECIES_INFO)) {
    if (key.toLowerCase() === lowerName || info.commonName.toLowerCase() === lowerName) {
      return info
    }
  }
  
  // Try partial match (e.g., "Bass" matches "Bass (Sea)")
  for (const [key, info] of Object.entries(SPECIES_INFO)) {
    if (key.toLowerCase().includes(lowerName) || lowerName.includes(key.toLowerCase().split(' ')[0])) {
      return info
    }
  }
  
  return null
}

// Get legal size for a species in a region
export function getSpeciesLegalSize(speciesId: string, region: RegionCode = 'uk_england') {
  return LEGAL_SIZE_RULES.find(r => r.speciesId === speciesId && r.region === region)
}

// Get bait suggestions for a species
export function getSpeciesBaits(speciesName: string): string[] {
  return BAIT_SUGGESTIONS[speciesName] || []
}

// Get rig suggestions for a species
export function getSpeciesRigs(speciesName: string): string[] {
  return RIG_SUGGESTIONS[speciesName] || []
}

// Get all species names for dropdown
export function getAllSpeciesNames(): string[] {
  return Object.keys(SPECIES_INFO).sort()
}
